services:
  nuxt:
    build:
      context: ./frontend
    container_name: nuxt
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - fastify

  fastify:
    build:
      context: ./backend
    container_name: fastify
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:14.1
    container_name: postgresFlanks
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
